name: run pre-commit

on:
  repository_dispatch:
    types: [run-pre-commit-command]
jobs:
  runprecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.event.client_payload.pull_request.head.repo.full_name}}
          ref: ${{github.event.client_payload.pull_request.head.ref}}
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install-tox
        run: python -m pip install --upgrade pre-commit
      - name: Slash Command Dispatch
        run: pre-commit run --all-files || (exit 0)
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Run pre-commit" -a
          git push
