name: tox

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tox:
    if: ${{ github.event.label.name != 'no-ci' }}
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [windows-latest, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check last commit message
        id: skip
        uses: atlwendy/retrieve-commit-messages-from-pr@v2
      - name: Set SHOULD_RUN flag
        run: echo ::set-env name=SHOULD_RUN::${{ steps.skip.outputs.shouldRun }}
        if: env.SHOULD_RUN == 'true'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        if: env.SHOULD_RUN == 'true'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-build-${{ matrix.python-version }}
      - name: install-tox
        run: python -m pip install --upgrade tox virtualenv setuptools pip
      - name: run-tox
        run: tox -e py
        if: env.SHOULD_RUN == 'true'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.python-version == '3.8' && matrix.os == 'ubuntu-18.04'
        with:
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
